# fly.toml app configuration file generated for pyraride on 2026-04-14T07:59:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pyraride'
primary_region = 'cdg'

[checks.health]
grace_period = "10s"
interval = "30s"
method = "get"
path = "/api/health"
port = 3_000
timeout = "10s"
type = "http"

[env]
NODE_ENV = "production"
PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3_000
min_machines_running = 1

  [http_service.concurrency]
  hard_limit = 250
  soft_limit = 200
  type = "requests"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
